export const CONFIG = {
  CRIT_MULTIPLIER: 1.5,
  RAND_MOD_MIN: 0.9,
  RAND_MOD_MAX: 1.1,
  BASE_CRIT_RATE: 0.05,
  POISON_DAMAGE_RATE: 0.08,

  EXP_CURVE_BASE: 100,
  EXP_CURVE_EXPONENT: 1.5,

  MAX_INVENTORY_SLOTS: 32,
  MAX_PARTY_SIZE: 4,

  SAVE_VERSION: 1,
  SAVE_SLOTS: 3,

  LOG_BUFFER_SIZE: 20,
} as const;
